 web:
   image: 'gitlab/gitlab-ee:latest'
   restart: always
   hostname: '${SQUASH_DOMAIN}'
   environment:
     GITLAB_OMNIBUS_CONFIG: |
       external_url 'http://${SQUASH_DOMAIN}'
       # Add any other gitlab.rb configuration here, each on its own line
   ports:
     - '80:80'
     - '22:22'
   volumes:
     - gitlab-config:/etc/gitlab
     - gitlab-logs:/var/log/gitlab
     - gitlab-data:/var/opt/gitlab

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
